In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
"Making an  one dimentional Array"
arr1= np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [5]:
" Making an multi dimentional Array"
arr2=np.array([(1,2),(2,3),(3,4)])
print(arr2)

[[1 2]
 [2 3]
 [3 4]]


In [8]:
"Shape and Size"
print(arr2.shape)
print(arr2.size)

(3, 2)
6


In [14]:
arr = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
"sum"
print(arr + arr2)

"sub"
print(arr - arr2)

"multiplication"
print(arr * arr2)
"division"
print(arr / arr2)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [16]:
"Multiplying Matrics"
arr1=np.array([(1,2),(2,3)])
arr2=np.array([(3,4),(4,5)])
print(arr1 @ arr2)

[[11 14]
 [18 23]]


In [17]:
arr = np.array([1, 4, 9, 16])

"Square root"
print(np.sqrt(arr))

"Exp"
print(np.exp(arr))


[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [63]:
arr = np.array([1, 2, 3, 4])

"Sum"
print(np.sum(arr))

"Mean"
print(np.mean(arr))

"Standard Deviation"
print(np.std(arr))
"median"
print(np.median(arr))
"varience"
print(np.var(arr))
"min"
print(np.min(arr))
"max"
print(np.max(arr))
"percentile"
print(np.percentile(arr,25))
print(np.percentile(arr,50))
print(np.percentile(arr,75))


10
2.5
1.118033988749895
2.5
1.25
1
4
1.75
2.5
3.25


In [24]:
"Reshaping Arrays"
aar=np.array([1,2,3,4,5,6])
arr2=arr.reshape(2,3)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [31]:
"transpose"
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [32]:
"Indexing"
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[5])

6


In [33]:
"Slicing"
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:3])

[2 3]


In [54]:
"problem Solution"
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
"p1- Extract the second row"
print(arr[1])
"p2- Extract the last two columns "
print(arr[:, -2:])
"p3- Find the sum of all elements"
print(arr.sum())
"p4- Replace all values in the second column with zeros"
arr[:,1]=0
print(arr)

[5 6 7 8]
[[ 3  4]
 [ 7  8]
 [11 12]]
78
[[ 1  0  3  4]
 [ 5  0  7  8]
 [ 9  0 11 12]]


In [55]:
"broadcasting"
arr = np.array([1, 2, 3, 4])

"Add a scalar value to an array"
finalarr = arr + 10
print(finalarr)


[11 12 13 14]


In [56]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6]])

arr1d = np.array([10, 20, 30])

"Add the 2D array and the 1D array"
finalarr2 = arr2d + arr1d
print(finalarr2)


[[11 22 33]
 [14 25 36]]
