In [3]:
"""

Z- Test 

"""
import numpy as np
from scipy import stats 

data = [12, 15, 14, 16, 15, 13, 15, 14, 16, 14]

population_mean = 14

population_std = 1.5

sample_mean = np.mean(data)

n = len(data)

z = (sample_mean - population_mean) / (population_std / np.sqrt(n))
p_value = 2 * (1 - stats.norm.cdf(abs(z)))

print("Z-statistic:", z)
print("P-value:", p_value)


Z-statistic: 0.8432740427115686
P-value: 0.39907519654823687


In [5]:
"""

T-Test One Sample

"""
t_statistic, p_value = stats.ttest_1samp(data, population_mean)

print("T-statistic:", t_statistic)
print("P-value:", p_value)


T-statistic: 1.0000000000000009
P-value: 0.34343639613791305


In [10]:
"""

T -test One Sample using logic

"""
sample_mean = np.mean(data)
sample_std = np.std(data)
t_statistic = (sample_mean - population_mean) / (sample_std / np.sqrt(n))
print("t-statistics",t_statistic)

t-statistics 1.0540925533894607


In [14]:
"""

T- test 2 Sample

"""
group1 = [68, 75, 70, 72, 71, 69, 73, 74, 70, 72]
group2 = [78, 85, 80, 82, 81, 79, 83, 84, 80, 82]

t_statistic, p_value = stats.ttest_ind(group1, group2)

print("T-statistic:", t_statistic)
print("P-value:", p_value)


T-statistic: -10.067340828210366
P-value: 8.053738934890404e-09


In [15]:
"""

T- test 2 Sample with logic

"""

mean1 = np.mean(group1)
mean2 = np.mean(group2)
std1 = np.std(group1)
std2 = np.std(group2)
n1 = len(group1)
n2 = len(group2)

pooled_std = np.sqrt(((n1 - 1) * std1**2 + (n2 - 1) * std2**2) / (n1 + n2 - 2))

t_statistic = (mean1 - mean2) / (pooled_std * np.sqrt(1/n1 + 1/n2))

print("Mean of Group 1:", mean1)
print("Mean of Group 2:", mean2)
print("Pooled Standard Deviation:", pooled_std)
print("T-statistic:", t_statistic)


Mean of Group 1: 71.4
Mean of Group 2: 81.4
Pooled Standard Deviation: 2.1071307505705477
T-statistic: -10.611908999450222


In [20]:
"""

T- test Paired 

"""
before = [12, 14, 15, 16, 14]
after = [15, 14, 17, 16, 18]

t_statistic, p_value = stats.ttest_rel(before, after)

print("T-statistic:", t_statistic)
print("P-value:", p_value)


T-statistic: -2.25
P-value: 0.08764517650339462


In [21]:
"""

T-test Paired with Logic

"""
differences = [after[i] - before[i] for i in range(len(before))]

mean_diff = np.mean(differences)
std_diff = np.std(differences)
n = len(differences)

t_statistic = mean_diff / (std_diff / np.sqrt(n))

print("Mean Difference:", mean_diff)
print("Standard Deviation of Differences:", std_diff)
print("T-statistic:", t_statistic)


Mean Difference: 1.8
Standard Deviation of Differences: 1.6
T-statistic: 2.5155764746872635


In [25]:
"""

Chi-Square Test 

"""
observed = np.array([[10, 20, 30], [6, 9, 17]])
print(observed)
chi2_statistic, p_value, dof, expected = stats.chi2_contingency(observed)

print("Chi-square statistic:", chi2_statistic)
print("P-value:", p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)


[[10 20 30]
 [ 6  9 17]]
Chi-square statistic: 0.27157465150403504
P-value: 0.873028283380073
Degrees of freedom: 2
Expected frequencies:
 [[10.43478261 18.91304348 30.65217391]
 [ 5.56521739 10.08695652 16.34782609]]


In [26]:
"""

Chi-Square Test with logic

"""
row_totals = observed.sum(axis=1)
col_totals = observed.sum(axis=0)
total = observed.sum()

expected = np.outer(row_totals, col_totals) / total

chi2_statistic = ((observed - expected) ** 2 / expected).sum()

dof = (observed.shape[0] - 1) * (observed.shape[1] - 1)

print("Chi-square statistic:", chi2_statistic)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)


Chi-square statistic: 0.27157465150403504
Degrees of freedom: 2
Expected frequencies:
 [[10.43478261 18.91304348 30.65217391]
 [ 5.56521739 10.08695652 16.34782609]]


In [27]:
"""

One Way Anova 

"""
group1 = [12, 14, 15, 16, 14]
group2 = [15, 16, 17, 18, 16]
group3 = [13, 14, 15, 13, 14]

f_statistic, p_value = stats.f_oneway(group1, group2, group3)

print("F-statistic:", f_statistic)
print("P-value:", p_value)


F-statistic: 7.000000000000002
P-value: 0.009666013301955795


In [29]:
"""

One Way Anova with logic

"""
mean1 = np.mean(group1)
mean2 = np.mean(group2)
mean3 = np.mean(group3)
overall_mean = np.mean(group1 + group2 + group3)

#SSB
SSB = len(group1) * (mean1 - overall_mean) ** 2 + len(group2) * (mean2 - overall_mean) ** 2 + len(group3) * (mean3 - overall_mean) ** 2

#SSW
SSW = sum((x - mean1) ** 2 for x in group1) + sum((x - mean2) ** 2 for x in group2) + sum((x - mean3) ** 2 for x in group3)

df_between = 2
df_within = (len(group1) - 1) + (len(group2) - 1) + (len(group3) - 1)

#meansquares
MSB = SSB / df_between
MSW = SSW / df_within

F = MSB / MSW
print("Between-Group Variability (SSB):", SSB)
print("Within-Group Variability (SSW):", SSW)
print("Mean Squares Between (MSB):", MSB)
print("Mean Squares Within (MSW):", MSW)
print("F-statistic:", F)


Between-Group Variability (SSB): 19.599999999999973
Within-Group Variability (SSW): 16.8
Mean Squares Between (MSB): 9.799999999999986
Mean Squares Within (MSW): 1.4000000000000001
F-statistic: 6.999999999999989
